- RFC0000-RFC-Process.md
Most the changes are just formatting - the important part is opening up submitting an RFC to the community.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/11)
> Open RFCs to the community

- X-Rejected/RFC0007-Weak-Aliases.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/17)
> PowerShell Committee response to RFC0007 Weak Aliases

- ISSUE_TEMPLATE.md
Adding a comment to remind RFC authors to indicate that an RFC is ready for voting
> Add pull request template

- 1-Draft/RFC0007-SSH-Remoting-Cmdlets.md
- 1-Draft/RFC0010-SSH-Remoting-Cmdlets.md
This RFC proposes PowerShell remoting cmdlet set additions for SSH based remoting.
> Add RFC 0010 to to define SSH based remoting cmdlet parameter sets

- 1-Draft/RFC0012-Enable-SSH-Remoting.md
This RFC is a proposal to create a new cmdlet (Enable-SSHRemoting) that will automatically install and configure SSH for PowerShell remoting.
> Adding new RFC Enable SSH Remoting

- 1-Draft/RFC0010-SSH-Remoting-Cmdlets.md
I updated this RFC to contain the latest SSH remoting parameter sets.
> Updated document with current SSH parameter set

- 1-Draft/RFC0016-Census-Telemetry.md
- 1-Draft/RFCxxxx-Census-Telemetry.md
> draft of census telemetry

- 1-Draft/RFC0013-PowerShellGet-PowerShellGallery_PreRelease_Version_Support.md
> Ps get versioning rfc

- CommunityCall/20161208 - Notes.md
- CommunityCall/README.md
@PowerShell/powershell-committee: can someone please merge if this looks okay?
> Adding notes from PowerShell Community Call #1

- 1-Draft/RFC0015-PowerShell-StartupConfig.md
Removed entire WSMAN config block from example config file
Reversed precedence
Add language which makes it clear that this spec is about preference rather than policy
Improved version handling to be done via filename rather than embedded in config file
> Additional Changes based on feedback

- CommunityCall/20161208 - Notes.md
> Adding links to the call recording and RFCs discussed

- 1-Draft/RFC####-Domain-Specific-Language-Specifications.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/57)
> DSL Specification

- 1-Draft/RFC0017-Domain-Specific-Language-Specifications.md
Revised the RFC for DSL specifications in PowerShell.
See issue #59 for comments.
This PR was originally [#60](https://github.com/PowerShell/PowerShell-RFC/pull/60)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/61)
> Revised dsl specification in both design and example

- 1-Draft/RFC-Get-StringHash.md
Introduce new cmdlet -  Get-StringHash.
Author of the idea @rkeithhill https://github.com/PowerShell/PowerShell/issues/2731
Related PR https://github.com/PowerShell/PowerShell/pull/3024
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/63)
> Add Get-StringHash

- 1-Draft/RFCXXXX-PowerShell-Core-Interop-Module.md
Sorry for all the commits - it was an iterative process ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/66)
> Interop Module(s) Which Patch(es) a PowerShell Runspace to Match The "Developed On" Platform of the PowerShell Code

- CommunityCall/20170126 - Chat Transcript.txt
- CommunityCall/README.md
- CommunityCall/RecurringCommunityCall.ics
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/75)
> Fix CommunityCall folder

- CommunityCall/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/77)
> Making menu option clearer per comment on #75

- CommunityCall/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/80)
> Added link to Mar 16th Community call recording

- 1-Draft/RFC0016-Census-Telemetry.md
simplify the RFC to capture only a hash of SMA.dll, OSVersion.VersionString, and GitCommitId on Console Host startup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/82)
> Recast RFC to rely on Application Insights rather than our own pipeline

- CommunityCall/README.md
Trivial PR to add our last community call as a link to YouTube in the CommunityCall folder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/91)
> Add April 20, 2017 call

- 1-Draft/RFC0020-DefaultFileEncoding.md
Added New-ModuleManifest 'Legacy' behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/95)
> Added New-ModuleManifest to the list of cmdlets in RFC0020 Default File Encoding

- CommunityCall/20170518_ChatTranscript.txt
- CommunityCall/README.md
Adding the chat transcript and a link to the YouTube video for our May 18, 2017 call.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/93)
> Add 20170518 Community Call

- CommunityCall/20170615_ChatTranscript.txt
- CommunityCall/20170720_ChatTranscript.txt
- CommunityCall/20170720_Notes.md
- CommunityCall/README.md
The branch name is misleading, this is for both June and July. YouTube videos should work (and have sound!), transcripts are there to accompany them. I've also added notes for the July call (which we should always take!).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/101)
> Add June and July community call links/transcripts

- CommunityCall/20171116_ChatTranscript.txt
- CommunityCall/20171116_Notes.md
- CommunityCall/README.md
@SteveL-MSFT I'm standardizing on `youtu.be`, I'll fix the others in another PR. :) 
Also, **new record**! Got this one out the same day! :)
> Add Nov community call

- CommunityCall/README.md
added text indicating topics include not only PSCore, but also EditorServices and ScriptAnalyzer
added Jan 18, 2018 YouTube link
reordered notes to be newest on top
> add Jan18th call

- CommunityCall/20180215_ChatTranscript.txt
- CommunityCall/20180215_Notes.md
- CommunityCall/README.md
Adding the call from yesterday, including transcript, video link, and notes.
> Add February community call

- CommunityCall/20180517_ChatTranscript.txt
- CommunityCall/20180517_Notes.md
- CommunityCall/README.md
> Add May Community Call notes, transcript, and YouTube link

- CommunityCall/20180621_ChatTranscript.txt
- CommunityCall/README.md
@SteveL-MSFT please merge if this looks good
> Add June community call

- 4-Experimental-Accepted/RFCXXXX-Snap-Preview.md
- 5-Final/RFC0027-Snap-Preview.md
> Snaps of Preview builds of PowerShell Core

- CommunityCall/20180719_ChatTranscript.txt
- CommunityCall/20180719_Notes.md
- CommunityCall/README.md
Either of you should feel free to merge once you've reviewed. Thanks!
> Add July community call

- CommunityCall/20180816_ChatTranscript.txt
- CommunityCall/20180816_Notes.md
- CommunityCall/README.md
> Add August community call

- CommunityCall/20180920_ChatTranscript.txt
- CommunityCall/20180920_Notes.md
- CommunityCall/README.md
> add Sept '18 Community Call

- CommunityCall/20181115_ChatTranscript.txt
- CommunityCall/20181115_Notes.md
- CommunityCall/README.md
Includes transcript, notes, and YouTube link.
> Add November 2018 community call

- CommunityCall/20181220_ChatTranscript.txt
- CommunityCall/20181220_Notes.md
- CommunityCall/README.md
> Add December 2018 Community call

- CommunityCall/20190117_ChatTranscript.txt
- CommunityCall/20190117_Notes.md
- CommunityCall/README.md
> Add Jan 2019 Community Call

- 2-Draft-Accepted/RFCNNNN-Command-Line-Suggestion-Infrastructure.md
- X-Withdrawn/RFC0032-Command-Line-Suggestion-Infrastructure.md
Submit RFC draft for a design of the command-line suggestion infrastructure.
/cc @SteveL-MSFT @TravisEz13 @PaulHigin @JamesWTruher
> A Design of the Command-line Suggestion Infrastructure

- CommunityCall/README.md
> change link to raw url

- RFC0000-RFC-Process.md
> update template fixing spelling error and adding section for user experience

- CommunityCall/20190620_ChatTranscript.txt
- CommunityCall/20190620_Notes.md
- CommunityCall/README.md
> Add May 2019 community call

- CommunityCall/README.md
- CommunityCall/notes/20190919_ChatTranscript.txt
- CommunityCall/notes/20190919_Notes.md
- CommunityCall/notes/20191017_ChatTranscript.txt
- CommunityCall/notes/20191017_Notes.md
Sept and Oct community calls with notes, links, and transcripts. Sorry for forgetting September, I went straight to vacation after it was over :)
> Add Sept and Oct 2019 community calls

- 1-Draft/RFCNNNN-ConvertFrom-Html.md
- X-Rejected/RFC0055-ConvertFrom-Html.md
Submitting ConvertFrom-Html RFC for consideration.
> Submitting ConvertFrom-Html RFC

- CommunityCall/README.md
- CommunityCall/notes/20200416_ChatTranscript.txt
- CommunityCall/notes/20200416_Notes.md
> April 2020 Community Call

- CommunityCall/README.md
- CommunityCall/notes/20200917_ChatTranscript.txt
- CommunityCall/notes/20200917_Notes.md
- CommunityCall/notes/20201015_ChatTranscript.txt
- CommunityCall/notes/20201015_Notes.md
@SteveL-MSFT @joeyaiello - Can you ack and merge.
> Sept/Oct 2020 Community Call

- CommunityCall/README.md
- CommunityCall/notes/20200716_ChatTranscript.txt
- CommunityCall/notes/20200716_notes.md
@SteveL-MSFT can you ack and merge.
> July 2020 Community Call

- CommunityCall/README.md
- CommunityCall/notes/20201217_ChatTranscript.txt
- CommunityCall/notes/20201217_Notes.md
@SteveL-MSFT and @joeyaiello, can you ack and merge.
> Move Dec 2020 notes/chat/readme to notes folder

- CommunityCall/README.md
- CommunityCall/notes/20210121_ChatTranscript.txt
- CommunityCall/notes/20210121_Notes.md
@SteveL-MSFT and @joeyaiello, Can you review and merge when you have time.
> January 21, 2021 Community Call

- CommunityCall/README.md
- CommunityCall/notes/20210218_ChatTranscript.txt
- CommunityCall/notes/20210218_Notes.md
Steve/Joey - Please review and merge.
> 20210218 - Feb PSCommunity Call

- CommunityCall/README.md
- CommunityCall/notes/20210318_ChatTranscript.txt
- CommunityCall/notes/20210318_Notes.md
@SteveL-MSFT/ @joeyaiello - Can you verify and merge
> Add March 2021 notes/chat/readme to CommunityCall

- CommunityCall/README.md
- CommunityCall/notes/20210520_Notes.md
@SteveL-MSFT and @joeyaiello - can you review and merge.
> May2021communitycall

- CommunityCall/README.md
- CommunityCall/notes/20210617_Notes.md
@SteveL-MSFT, @joeyaiello - can you review and merge please.
> PS Community Call - June 2021

- 2-Draft-Accepted/Readme.md
Forgot to remove this empty folder in #290
> Remove empty 2-Draft-Accepted

- CommunityCall/README.md
- CommunityCall/notes/20210715_Notes.md
@SteveL-MSFT, can you review and merge.
> Added notes/readme for PSCommCall-20210715

- CommunityCall/README.md
- CommunityCall/notes/20210819_Notes.md
@SteveL-MSFT & @joeyaiello - this is ready merge after your approval
> Move Aug CommCall notes to notes folder, update readme.

- CommunityCall/README.md
- CommunityCall/notes/20211118_Notes.md
@SteveL-MSFT, the November PS Community Call is ready for review and merge.
>  Nov PSCommCall notes and readme

- CommunityCall/README.md
- CommunityCall/notes/20220120_Notes.md
@SteveL-MSFT / @mgreenegit  Readme and Notes update for Jan Community Call
> Publishing Jan 2022 Community Call

- CommunityCall/README.md
- CommunityCall/notes/20220217_Notes.md
@SteveL-MSFT / @mgreenegit -- please review and merge.
> Feb 17th PS Community Call

- CommunityCall/README.md
- CommunityCall/notes/20220421_Notes.md
@SydneyhSmith - can you review and merge the April Community Call please.
> adding April 2022 Community Call

- CommunityCall/README.md
- CommunityCall/notes/20220519_Notes.md
@SydneyhSmith - Can you please review and merge
> adding May PSCommCall

- CommunityCall/README.md
- CommunityCall/notes/20220721_Notes.md
Hey @SydneyhSmith  - ready for your review and merge.
> Adding July 21 2022 PSCommunity Call

- CommunityCall/README.md
- CommunityCall/notes/20220818_Notes.md
@SydneyhSmith - Can you review and merge please
> August 2022 Community Call

- CommunityCall/README.md
@SteveL-MSFT / @SydneyhSmith - September Community Call is ready for review and merge.
> September 2022 Community Call

- CommunityCall/README.md
- CommunityCall/notes/20221020_Notes.md
@SteveL-MSFT / @StevenBucher98 - Please review and merge the October 2022 Community Call.
> Oct2022 Community Call

- Archive/Draft/RFCNNNN-PowerShell-LocalSession-Configuration.md
- Final/RFC0064-PowerShell-LocalSession-Configuration.md
> Add first draft of local session configuration

- CommunityCall/README.md
- CommunityCall/notes/20221117_Notes.md
> added November 2022 Community Call

- CommunityCall/README.md
- CommunityCall/notes/20230119_Notes.md
@SteveL-MSFT, @StevenBucher98 - Can you review and merge the Jan 2023 community call ;)
> January 2023 Community Call

- CommunityCall/README.md
- CommunityCall/notes/20230420_Notes.md
@StevenBucher98 @SydneyhSmith - Can you review and merge please ;)
> Adding April Community Call

- CommunityCall/README.md
- CommunityCall/notes/20230518_Notes.md
@SydneyhSmith / @StevenBucher98 - Ready for review and merge ;)
> May Community Call

- CommunityCall/README.md
- CommunityCall/notes/20230615_Notes.md
@StevenBucher98 / @SteveL-MSFT - Please review and merge - thank you.
> adding June Community Call

- CommunityCall/README.md
- CommunityCall/notes/20230720_Notes.md
@StevenBucher98 / @SydneyhSmith - can you review and merge? THX
> adding July Community Call

- CommunityCall/README.md
- CommunityCall/notes/20230817_Notes.md
@StevenBucher98 / @SydneyhSmith  - Please review and merge.
> Adding August 17th 2023 Community Call

- CommunityCall/README.md
@StevenBucher98 - Please review and merge the chat transcript notes and readme.
> Adding August Community Chat Transcript

- CommunityCall/README.md
- CommunityCall/notes/20230921_ChatTranscript.md
- CommunityCall/notes/20230921_Notes.md
@StevenBucher98 / @SydneyhSmith - can you review and merge please? :)
> September Community Call

- CommunityCall/README.md
- CommunityCall/notes/20231019_ChatTranscript.md
- CommunityCall/notes/20231019_Notes.md
@StevenBucher98 - Could you review and merge? -- thank you!
> October Community Call

- CommunityCall/README.md
- CommunityCall/notes/20231130_ChatTranscript.md
- CommunityCall/notes/20231130_Notes.md
@StevenBucher98 / @SydneyhSmith - Can you review and merge? -- Thank you!!!
> November Community Call

- CommunityCall/README.md
- CommunityCall/notes/20240118_ChatTranscript.md
- CommunityCall/notes/20240118_Notes.md
@StevenBucher98 / @SydneyhSmith  - Hi! Can you please review and merge the community call -- Thank you!
> Adding Jan 2024 Community Call

- CommunityCall/README.md
- CommunityCall/notes/20240215_ChatTranscript.md
- CommunityCall/notes/20240215_Notes.md
@StevenBucher98 / @SydneyhSmith - Can you review and merge -- especially the new note section. Thank you!!
> Adding Feb Community Call

- CommunityCall/README.md
- CommunityCall/notes/20240321_ChatTranscript.md
- CommunityCall/notes/20240321_Notes.md
@SydneyhSmith / @StevenBucher98 - Can you review (especially the chat/notes) and merge?  Thank you!
> Adding March Community Call

- CommunityCall/README.md
- CommunityCall/notes/20240418_ChatTranscript.md
- CommunityCall/notes/20240418_Notes.md
@StevenBucher98 - Can you review and merge?
> Adding April PS Community Call

- CommunityCall/README.md
- CommunityCall/notes/20240516_ChatTranscript.md
- CommunityCall/notes/20240516_Notes.md
@SydneyhSmith / @StevenBucher98  - Can you review the notes and merge?  Thank you!!
> Adding May 16th 2024 Community Call

- CommunityCall/README.md
- CommunityCall/notes/20240620_ChatTranscript.md
- CommunityCall/notes/20240620_Notes.md
@SydneyhSmith - Can you review and merge? - Thank you!!
> June 2024 Community Call

- CommunityCall/README.md
- CommunityCall/notes/20240718_ChatTranscript.md
- CommunityCall/notes/20240718_Notes.md
@StevenBucher98 / @SydneyhSmith  can you review and merge please?
> July 2024 Community Call

- CommunityCall/README.md
- CommunityCall/notes/20240815_ChatTranscript.md
- CommunityCall/notes/20240815_Notes.md
@SydneyhSmith / @StevenBucher98  - Can you review and merge?  Thank you!
> August 2024 Community Call

- CommunityCall/README.md
- CommunityCall/notes/20240918_ChatTranscript.md
- CommunityCall/notes/20240918_Notes.md
@SydneyhSmith / @StevenBucher98  - Can you review and merge? Thanks!!
> September 2024 Community Call

- CommunityCall/README.md
- CommunityCall/notes/20241017_ChatTranscript.md
- CommunityCall/notes/20241017_Notes.md
@SydneyhSmith / @StevenBucher98 - Can you review and merge this pr?  Thank you!!!
> October 2024 Community Call

- CommunityCall/README.md
- CommunityCall/notes/20250116_ChatTranscript.md
- CommunityCall/notes/20250116_Notes.md
@StevenBucher98 - Can you review and merge?  Thank you!!
> Community Call Jan-2025

- CommunityCall/README.md
- CommunityCall/notes/20250220_ChatTranscript.md
- CommunityCall/notes/20250220_Notes.md
@StevenBucher98 / @SydneyhSmith -- Can you review and merge the Feb community call -- Thank you!
> Feb Community Call

- CommunityCall/README.md
- CommunityCall/notes/20250515_ChatTranscript.md
- CommunityCall/notes/20250515_Notes.md
@SydneyhSmith / @StevenBucher98 - Can you review and merge please?  Thank you!
> May PS Community Call

- CommunityCall/README.md
- CommunityCall/notes/20250619_ChatTranscript.md
- CommunityCall/notes/20250619_Notes.md
@StevenBucher98 / @SydneyhSmith - Can you review and merge?  Thank you!!
> June 19th Community Call

- CommunityCall/README.md
- CommunityCall/notes/20250821_ChatTranscript.md
- CommunityCall/notes/20250821_Notes.md
@SydneyhSmith / @StevenBucher98 - Can you review and merge the community call?  Thank you and have a great weekend!
> August 2025 Community Call
