1-Draft/RFC0005-Typed-Interprocess-communication.md
1-Draft/RFC0006-Universal-Parsing-and-Piping.md

More completely separating the interface (command-line) from the underlying process-executor allows for a more uniform handling of processes, which would enable the usage of non-text typed-streams in inter-process communication which, in turn, will increase reliability and eliminate an entire class of vulnerabilities.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/12)

Two RFCs entailing changes to PowerArchiver's internals.

---

1-Draft/RFC0007-Weak-Aliases.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/13)

Add Weak Alias RFC

---

1-Draft/RFC0008-Glob-for-Native-Tools.md
1-Draft/RFC0009-Glob-for-Native-Tools.md

This RFC proposes the extension of globbing to native tools for PowerShell on Linux (initially).
The prototype for this exists at https://github.com/PowerShell/PowerShell/pull/2325.
/cc @vors @lzybkr @jpsnover

Add RFC 0009 to extend globbing to native tools

---

1-Draft/RFC0011-Dot-Referencing-With-Static-Integers.md
1-Draft/RFCXXXX-Dot-Referencing-With-Static-Integers.md

This RFC is to allow for member invocation on static integers without brackets.

New RFC - Dot referencing with decimal integer literals

---

1-Draft/DefaultFileEncoding.md

An RFC was requested in response to https://github.com/PowerShell/PowerShell/issues/707, so here it is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/70)

rationalizing the file encoding story for cmdlets

---

1-Draft/RFC0018-Get-StringHash.md

Main question is should we join `Get-FileHash` and `Get-StringHash` into `Get-Hash` or no?
In the PR I try join the cmdlets into one.
/cc @SteveL-MSFT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/79)

Corrections RFC0018 after initial discussion

---

RFC0000-RFC-Process.md

Based on my first experience. 🐔 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/81)

Correction of roles and workflow

---

RFC0000-RFC-Process.md

As discussed by the @PowerShell/powershell-committee in our last community call, this is a first attempt at moving to a model where comments are reviewed in a pull request. 
This process requires that we make a `Review - Open for comments` label. 
Also, if it makes sense to anyone else, I want to write a "quick start guide" for writing an RFC that has a lot less formal language and is more step-by-step.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/87)

first pass of RFC refactor

---

1-Draft/RFC0020-DefaultFileEncoding.md

Title pretty much says it all: we want to have BOM-less UTF-8 be the default everywhere for PowerShell 6.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/96)

Update encoding RFC to default BOM-less UTF-8 everywhere

---

1-Draft/RFC0020-DefaultFileEncoding.md

Changes:
* Change to `Microsoft.PowerShell.Encoding`
* Change `Legacy` to `WindowsLegacy`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/98)

Simplify types and enums in default encoding RFC

---

CommunityCall/20180315_ChatTranscript.txt
CommunityCall/20180315_Notes.md
CommunityCall/README.md

Adding transcript, notes, and YouTube link for the March 2018 community call. 
Working on our turnaround time, PR published before noon on the day of the call. 😊

Add March Community Call

---

2-Draft-Accepted/RFCNNN-Performance-Testing.md

Performance Testing

---

2-Draft-Accepted/RFCXXXX-MSI-Installation-Path.md
4-Experimental-Accepted/RFCXXXX-MSI-Installation-Path.md

The title should be relatively self-explanatory (as well as the motivation in the doc itself), but basically we need to change the install path of PowerShell in order to support Microsoft Update. 
We recognize that this is a breaking change, but it also should be a much more sustainable model for people who update frequently. 
Please bring on the feedback. :)

Add RFC draft for changing the MSI install path of PowerShell Core

---

2-Draft-Accepted/RFC0025-PSCore6-and-Windows-Modules.md
2-Draft-Accepted/RFCNNNN-PSCore6-and-Windows-Modules.md

Enable discovery of compatible Windows PowerShell modules in PSCore6

---

2-Draft-Accepted/RFCNNNN-Support-Experimental-Features.md
4-Experimental-Accepted/RFC0029-Support-Experimental-Features.md

This RFC is for adding support to Experimental Features in PowerShell.
/cc @dantraMSFT

Support Experimental Features in PowerShell

---

5-Final/RFC0025-PSCore6-and-Windows-Modules.md

Change **PSEditions** column name to **PSEdition** in 'RFC0025-PSCore6-and-Windows-Modules.md'.

Change 'PSEditions' column name to 'PSEdition'.

---

1-Draft/RFC0000-Experimental-Feature-User-Experience.md

Draft of experimental feature user experience RFC

---

1-Draft/RFC0002-Generalized-Splatting.md
2-Draft-Accepted/RFC0002-Generalized-Splatting.md

This includes:
* explicit override of the relaxed splatting operator (for both cmdlet and .NET method invocation)
* moved "Modifying hashtables for splatting" to the Alternate Proposals section
* a couple typo edits

Edits to RFC0002 after committee discussion

---

2-Draft-Accepted/RFC00NN-PowerShellCore-Installer-Module.md
X-Withdrawn/RFC0031-PowerShellCore-Installer-Module.md

The RFC should explain everything, but this is a helper module that we should ship on the Gallery to aid admins/users with installing/updating/servicing PowerShell Core, as well as to register its remoting endpoint, from Windows PowerShell.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-rfc/97)

PowerShell Core Installer/Utility Module

---

1-Draft/RFCNNNN-Expose-ForEach-Where-Methods-as-Operators.md
X-Rejected/RFC0034-Expose-ForEach-Where-Methods-as-Operators.md

As originally discussed in https://github.com/PowerShell/PowerShell/issues/6576

Expose the .ForEach() and .Where() methods as regular PowerShell operators

---

1-Draft/RFCNNNN-#Requires-Additions.md
2-Draft-Accepted/RFC0035-#Requires-Additions.md

Add new functionality and restrictions to #requires 

---

1-Draft/RFCNNNN-AdditionalTelemetry.md
2-Draft-Accepted/RFC0036-AdditionalTelemetry.md

RFC0036-AdditionalTelemetry

---

PULL_REQUEST_TEMPLATE.md

Add language to make providing examples mandatory

---

5-Final/RFC0020-DefaultFileEncoding.md

Fix markdown code formatting in **RFC0020-DefaultFileEncoding.md**.

Fix code formatting.

---

2-Draft-Accepted/RFC0040-PowerShell-as-Login-Shell.md
2-Draft-Accepted/RFCnnnn-PowerShell-as-Login-Shell.md

Enable use of pwsh as login shell

---

1-Draft/RFCXXXX-Policy.md
2-Draft-Accepted/RFC0041-Policy.md

The main goal here is to describe various policy and setting fall-back behavior:  
1. When things like `-settingsfile` will be allowed to overwrite, what type of settings.
2. When PowerShell Core will use Windows PowerShell Policy, and how.
3. Where various policies/settings are read from.

PowerShell Core Policy

---

1-Draft/RFCXXXX-Send-MailMessage.md
5-Final/RFC0042-Send-MailMessage.md

RFC to  obsolete `Send-MailMessage`

---

1-Draft/RFCnnnn-ForEach-Parallel-Cmdlet.md
4-Experimental-Accepted/RFC0044-ForEach-Parallel-Cmdlet.md

Submit draft of RFC for ForEach-Object -Parallel proposal

---

2-Draft-Accepted/RFC0041-Policy.md

[RFC0041-Policy](https://github.com/PowerShell/PowerShell-RFC/blob/master/2-Draft-Accepted/RFC0041-Policy.md) specifies policy reg keys other than what current code is using,
so implementing RFC as it is will end up as a breaking change.
As confirmed by RFC owner @TravisEz13, the RFC was never intended to contain a breaking change,
so RFC has to be updated to avoid a breaking change.

Updating RFC0041 - PowerShell Core Policy

---

1-Draft/RFCxxxx-Ternary-Operator.md
4-Experimental-Accepted/RFC0045-Ternary-Operator.md

Related issue: https://github.com/PowerShell/PowerShell/issues/3239
Related PRs: 
- Draft PR: https://github.com/PowerShell/PowerShell/pull/10161
- Official PR: https://github.com/PowerShell/PowerShell/pull/10367
The PowerShell Committee [has approved to add the ternary operator to the language](https://github.com/PowerShell/PowerShell/issues/3239#issuecomment-517048192), and this RFC is mainly to capture the design points and implementation details.

Support the ternary operator in PowerShell language

---

1-Draft/RFC0000-Chain-Operators.md
4-Experimental-Accepted/RFC0046-Chain-Operators.md

Pipeline Chain Operators (&& / ||)

---

1-Draft/RFCXXXX-RFC-Invoke-DscResource.md
4-Experimental-Accepted/RFC0047-RFC-Invoke-DscResource.md

This is an RFC to add support for an Invoke-DscResource in PowerShell 7.
Since `Get-DscResource` and `Configuration` have been fixed, this RFC is only to add something similar in syntax than the WMF 5.1's `Invoke-DscResource`, but not using the LCM or CIM, and only consuming PowerShell resource directly.
This RFC mainly specify an MVP (Minimum Viable Product), but feel free to comment or add in the `out of scope` section, what should come next.

Invoke-DscResource bypassing LCM for PS7

---

1-Draft/RFCxxxx-PSModulePath.md
5-Final/RFC0049-PSModulePath.md

Define behavior of PSModulePath in PS7 when starting and when starting Windows PowerShell

Draft of PSModulePath behavior in PS7

---

1-Draft/RFCNNN-Null-conditional-operators.md
5-Final/RFC0051-Null-conditional-operators.md

The concept has been discussed in issue https://github.com/PowerShell/PowerShell/issues/3240

Null conditional operators for coalescing, assignment and member access

---

1-Draft/RFCNNNN-Notification-On-Version-Update.md
5-Final/RFC0052-Notification-On-Version-Update.md

Support notification on `pwsh` startup when a new update is available.
Today, to find out whether a new version of PowerShell is available, one has to check the release page of the `PowerShell\PowerShell` repository, or depend on communication channels like `twitter` or `GitHub Notifications`. It would be convenient if `pwsh` itself can notify the user of a new update on startup.

Support notification on `pwsh` startup when a new update is available

---

1-Draft/RFCNNNN-PowerShell-IoT-Module.md
X-Withdrawn/RFCNNNN-PowerShell-IoT-Module.md

PowerShell IoT module RFC

---

1-Draft/RFCNNNN-Optional-Features.md
X-Rejected/RFC0058-Optional-Features.md

This RFC was originally proposed as part of a collection of RFCs in PR #187. I am separating those RFCs into separate PRs to better adhere to the RFC process.

Optional Features

---

1-Draft/RFCNNNN-Dispose-Script-Block.md
2-Draft-Accepted/RFC0059-Cleanup-Script-Block.md

For a working implementation of this RFC, please see https://github.com/PowerShell/PowerShell/pull/9900.

Add `Cleanup {}` named function block

---

1-Draft/RFCnnnn-Alias-Policy.md
X-Rejected/RFC0061-Alias-Policy.md

Address https://github.com/PowerShell/PowerShell/issues/5870

Alias policy RFC

---

CommunityCall/README.md

Adds the time of the community call to the ReadMe for the community call so that it can be more easily determined.
Includes a link to http://www.timebie.com/std/pdt.php?q=9.5 which appears to convert into the users local time and lists common worldwide times near the bottom of the page.

Add the time of the Community Call

---

RFC0000-RFC-Process.md

This PR reworks the RFC process to conform to the updated governance of Working Groups (WGs). 
For more context, see PowerShell/PowerShell#14603 and [this blog post](https://devblogs.microsoft.com/powershell/powershell-working-groups/).

Updated governance and process: Working Groups (WGs)
